### ISSUE TITLE
ERROR in Build: ImportError: No module named tempita

### ISSUE THREAD

**Issue by fferri** [CoppeliaRobotics/v_repExtRosInterface#11]
_From @mzahana on December 5, 2016 11:25_

I get the following error when I run ```catkin build``` ,
```sh
Errors     << vrep_ros_interface:make /home/abdkadma/ros_ws/logs/vrep_ros_interface/build.make.001.log
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/abdkadma/python-packages/v_repStubsGen/__main__.py", line 1, in <module>
    from main import *
  File "/home/abdkadma/python-packages/v_repStubsGen/main.py", line 2, in <module>
    import tempita
ImportError: No module named tempita
make[2]: *** [generated/stubs.cpp] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/v_repExtRosInterface.dir/all] Error 2
make: *** [all] Error 2

```

What could be the problem?

_Copied from original issue: fferri/v_repExtRosInterface#11_

**Comment by fferri** [comment]
_From @mzahana on December 5, 2016 11:33_

Solved by installing ```python-tempita``` module by,

```sh
sudo apt-get update
sudo apt-get install python-tempita
```
