### ISSUE TITLE
Compiling issue: lxml.etree.XMLSyntaxError: Attribute name redefined

### ISSUE THREAD

**Issue by fferri** [CoppeliaRobotics/v_repExtRosInterface#13]
_From @ricsp on May 23, 2017 22:12_

Hi,
I have tried compiling the ros interface but I get the following error. Can you please help me?
I am on kinetic and Ubuntu 16.04
Thanks.
Riccardo

> Traceback (most recent call last):
>   File "/home/rspica/catkin_ws/src/vrep_ros_interface/external/v_repStubsGen/generate.py", line 67, in <module>
>     plugin = parse(args.xml_file)
>   File "/home/rspica/Repositories/vrep_ros_interface/external/v_repStubsGen/parse.py", line 5, in parse
>     tree = etree.parse(xml_file)
>   File "src/lxml/lxml.etree.pyx", line 3427, in lxml.etree.parse (src/lxml/lxml.etree.c:85131)
>   File "src/lxml/parser.pxi", line 1782, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:124005)
>   File "src/lxml/parser.pxi", line 1808, in lxml.etree._parseDocumentFromURL (src/lxml/lxml.etree.c:124374)
>   File "src/lxml/parser.pxi", line 1712, in lxml.etree._parseDocFromFile (src/lxml/lxml.etree.c:123169)
>   File "src/lxml/parser.pxi", line 1115, in lxml.etree._BaseParser._parseDocFromFile (src/lxml/lxml.etree.c:117533)
>   File "src/lxml/parser.pxi", line 573, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:110510)
>   File "src/lxml/parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:112276)
>   File "src/lxml/parser.pxi", line 613, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:111124)
> lxml.etree.XMLSyntaxError: Attribute name redefined, line 4, column 76

_Copied from original issue: fferri/v_repExtRosInterface#13_

**Comment by fferri** [comment]
Thanks for reporting this issue
