### ISSUE TITLE
build error: xsltproc: OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by fferri** [CoppeliaRobotics/v_repExtRosInterface#15]
_From @xukuanHIT on August 3, 2017 8:43_

Hi, it happened some error when I run "catkin build" 
running external/pycpp/pycpp
running external/pycpp/pycpp
no lua file defined. skipping lua_to_xml
no lua file defined. skipping gen_reference_xml
running xsltproc
Traceback (most recent call last):
  File "/home/xukuan/catkin_ws/src/vrep_ros_interface/external/v_repStubsGen/generate.py", line 96, in <module>
    runprogram('xsltproc', '-o', output('reference.html'), rel('xsl/reference.xsl'), input_xml)
  File "/home/xukuan/catkin_ws/src/vrep_ros_interface/external/v_repStubsGen/generate.py", line 50, in runprogram
    runsubprocess(what, [what] + list(args))
  File "/home/xukuan/catkin_ws/src/vrep_ros_interface/external/v_repStubsGen/generate.py", line 38, in runsubprocess
    child = subprocess.Popen(args)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
CMakeFiles/v_repExtRosInterface.dir/build.make:61: recipe for target 'generated/stubs.cpp' failed
make[2]: *** [generated/stubs.cpp] Error 1
make[2]: *** Deleting file 'generated/stubs.cpp'
CMakeFiles/Makefile2:784: recipe for target 'CMakeFiles/v_repExtRosInterface.dir/all' failed
make[1]: *** [CMakeFiles/v_repExtRosInterface.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
What should I do ?

_Copied from original issue: fferri/v_repExtRosInterface#15_

**Comment by fferri** [comment]
you need xsltproc (`sudo apt install xsltproc`)

**Comment by fferri** [comment]
_From @xukuanHIT on August 3, 2017 8:48_

OK, it works. Thank you vrey much!
